/**
 * Ported from src/M365-Assess/Setup/PermissionDefinitions.ps1
 * ($script:RequiredGraphPermissions). Authoritative matrix:
 * docs/reference/PERMISSIONS.md (generated by scripts/Build-PermissionsMatrix.ps1
 * — do not duplicate scope lists elsewhere).
 *
 * Requesting the FULL read-only set at first consent is deliberate: admin
 * consent grants everything requested in one interaction, and re-consent for
 * newly added scopes requires a Global Administrator to intervene again. One
 * consent, complete coverage.
 */

export interface RequiredScope {
  name: string;
  purpose: string;
}

export const REQUIRED_GRAPH_SCOPES: readonly RequiredScope[] = [
  {
    name: "Application.Read.All",
    purpose: "App registrations, service principals, OAuth permission grants",
  },
  { name: "AuditLog.Read.All", purpose: "Sign-in logs and directory audit events" },
  { name: "Channel.ReadBasic.All", purpose: "Teams channels" },
  {
    name: "DeviceManagementApps.Read.All",
    purpose: "Intune audit events including device wipe/retire/delete actions",
  },
  {
    name: "DeviceManagementConfiguration.Read.All",
    purpose:
      "Configuration profiles, compliance policies, Multi-Admin Approval policies",
  },
  {
    name: "DeviceManagementManagedDevices.Read.All",
    purpose: "Managed device inventory and compliance state",
  },
  {
    name: "DeviceManagementRBAC.Read.All",
    purpose: "Intune RBAC role definitions and assignments (scope tag audit)",
  },
  {
    name: "Directory.Read.All",
    purpose: "Devices, admin units, role templates",
  },
  {
    name: "Domain.Read.All",
    purpose: "All domains registered in the tenant",
  },
  {
    name: "Group.Read.All",
    purpose: "All groups including Microsoft 365 and security groups",
  },
  {
    name: "MailboxSettings.Read",
    purpose: "Mailbox-level settings (forwarding, audit, locale) via Graph",
  },
  {
    name: "OrgSettings-Forms.Read.All",
    purpose: "Microsoft Forms tenant-level settings",
  },
  {
    name: "Organization.Read.All",
    purpose: "Tenant org details, verified domains, hybrid config",
  },
  {
    name: "Policy.Read.All",
    purpose: "Conditional Access, auth methods, token lifetime, password policies",
  },
  { name: "Reports.Read.All", purpose: "Microsoft 365 usage reports" },
  {
    name: "RoleManagement.Read.Directory",
    purpose: "Entra directory role assignments and PIM eligibility",
  },
  {
    name: "SecurityEvents.Read.All",
    purpose: "Secure Score, improvement actions, security alerts",
  },
  {
    name: "SharePointTenantSettings.Read.All",
    purpose: "SharePoint and OneDrive tenant-level settings",
  },
  { name: "Sites.Read.All", purpose: "SharePoint site enumeration and metadata" },
  { name: "Team.ReadBasic.All", purpose: "Enumerate all Teams" },
  { name: "TeamMember.Read.All", purpose: "Teams membership details" },
  {
    name: "TeamSettings.Read.All",
    purpose: "Teams tenant-level settings and policies",
  },
  {
    name: "TeamworkAppSettings.Read.All",
    purpose: "Teams app permission and setup policies",
  },
  {
    name: "User.Read.All",
    purpose: "User profiles, sign-in activity, license assignments",
  },
  {
    name: "UserAuthenticationMethod.Read.All",
    purpose: "MFA and passwordless authentication methods per user",
  },
];
