<#
.SYNOPSIS
    Generates docs/reference/PERMISSIONS.md from the orchestrator's section-to-scope map
    and the consent-helper's permission definitions.
.DESCRIPTION
    Reads two source-of-truth files:
      - src/M365-Assess/Orchestrator/AssessmentMaps.ps1 (delegated Graph scopes
        per section, services touched per section)
      - src/M365-Assess/Setup/PermissionDefinitions.ps1 (Graph application
        permissions, EXO RBAC role groups, Purview/Compliance directory roles)

    Inverts the per-permission annotations into a per-section view and emits
    a markdown matrix at docs/reference/PERMISSIONS.md. CI runs this with -Check to
    enforce that the doc never drifts from the source maps.

    If you change the section-to-scope map, re-run this script and commit the
    regenerated docs/reference/PERMISSIONS.md alongside the map change. CI will fail
    the PR otherwise.
.PARAMETER RepoRoot
    Repository root. Defaults to the parent of the script's directory.
.PARAMETER OutputPath
    Where to write the doc. Defaults to docs/reference/PERMISSIONS.md under RepoRoot.
.PARAMETER Check
    Compare existing OutputPath content against freshly-generated output.
    Exit 0 if they match, exit 1 with a diff summary if they don't.
    Used by CI to enforce the doc-stays-in-sync invariant.
.EXAMPLE
    PS> ./scripts/Build-PermissionsMatrix.ps1
    Regenerates docs/reference/PERMISSIONS.md.
.EXAMPLE
    PS> ./scripts/Build-PermissionsMatrix.ps1 -Check
    Used by CI; exits 1 if the doc is out of sync.
#>
[CmdletBinding()]
param(
    [Parameter()]
    [string]$RepoRoot = (Split-Path -Parent (Split-Path -Parent $PSCommandPath)),

    [Parameter()]
    [string]$OutputPath,

    [Parameter()]
    [switch]$Check
)

if (-not $OutputPath) {
    # docs/reference/PERMISSIONS.md moved to docs/reference/PERMISSIONS.md in #906 (docs
    # consolidation). Updated default reflects the new canonical location.
    $OutputPath = Join-Path -Path $RepoRoot -ChildPath 'docs/reference/PERMISSIONS.md'
}

# ------------------------------------------------------------------
# Load source maps
# ------------------------------------------------------------------
$mapsScript = Join-Path -Path $RepoRoot -ChildPath 'src/M365-Assess/Orchestrator/AssessmentMaps.ps1'
$permsScript = Join-Path -Path $RepoRoot -ChildPath 'src/M365-Assess/Setup/PermissionDefinitions.ps1'

if (-not (Test-Path -LiteralPath $mapsScript)) {
    throw "AssessmentMaps.ps1 not found at $mapsScript"
}
if (-not (Test-Path -LiteralPath $permsScript)) {
    throw "PermissionDefinitions.ps1 not found at $permsScript"
}

. $mapsScript
. $permsScript

$maps = Get-AssessmentMaps
$serviceMap = $maps.SectionServiceMap
$scopeMap = $maps.SectionScopeMap

# ------------------------------------------------------------------
# Invert per-permission annotations into per-section view
# ------------------------------------------------------------------
function ConvertTo-SectionMap {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)] [object[]]$Entries,
        [Parameter(Mandatory)] [string]$NameKey
    )
    $bySection = @{}
    foreach ($entry in $Entries) {
        $sectionList = $entry.Sections -split ',' | ForEach-Object { $_.Trim() }
        foreach ($section in $sectionList) {
            if (-not $bySection.ContainsKey($section)) {
                $bySection[$section] = New-Object -TypeName System.Collections.Generic.List[psobject]
            }
            $bySection[$section].Add([pscustomobject]@{
                    Name   = $entry.$NameKey
                    Reason = $entry.Reason
                })
        }
    }
    return $bySection
}

$appPermsBySection = ConvertTo-SectionMap -Entries $script:RequiredGraphPermissions      -NameKey 'Name'
$exoRolesBySection = ConvertTo-SectionMap -Entries $script:RequiredExoRoleGroups         -NameKey 'RoleGroup'
$compRolesBySection = ConvertTo-SectionMap -Entries $script:RequiredComplianceRoles      -NameKey 'DisplayName'

# ------------------------------------------------------------------
# Discover full section list (union of all maps)
# ------------------------------------------------------------------
$allSections = New-Object -TypeName System.Collections.Generic.SortedSet[string]
foreach ($s in $serviceMap.Keys)        { [void]$allSections.Add($s) }
foreach ($s in $scopeMap.Keys)          { [void]$allSections.Add($s) }
foreach ($s in $appPermsBySection.Keys) { [void]$allSections.Add($s) }
foreach ($s in $exoRolesBySection.Keys) { [void]$allSections.Add($s) }
foreach ($s in $compRolesBySection.Keys) { [void]$allSections.Add($s) }

# ------------------------------------------------------------------
# Build the markdown
# ------------------------------------------------------------------
$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('# Permissions matrix')
[void]$sb.AppendLine()
[void]$sb.AppendLine('> **Generated by `scripts/Build-PermissionsMatrix.ps1`. Do not edit by hand.**')
[void]$sb.AppendLine('>')
[void]$sb.AppendLine('> Sources:')
[void]$sb.AppendLine('> - `src/M365-Assess/Orchestrator/AssessmentMaps.ps1` (services + delegated Graph scopes per section)')
[void]$sb.AppendLine('> - `src/M365-Assess/Setup/PermissionDefinitions.ps1` (app-only Graph permissions, EXO RBAC role groups, Purview/Compliance directory roles)')
[void]$sb.AppendLine('>')
[void]$sb.AppendLine('> CI runs `Build-PermissionsMatrix.ps1 -Check` and fails any PR that modifies the source maps without regenerating this doc.')
[void]$sb.AppendLine()
[void]$sb.AppendLine('## Overview')
[void]$sb.AppendLine()
[void]$sb.AppendLine('| Section | Services | Delegated scopes | App permissions | EXO RBAC groups | Purview/Compliance roles |')
[void]$sb.AppendLine('|---|---|---|---|---|---|')

foreach ($section in $allSections) {
    $services = if ($serviceMap.ContainsKey($section) -and $serviceMap[$section].Count -gt 0) {
        ($serviceMap[$section] -join ', ')
    } else { '—' }
    $scopeCount = if ($scopeMap.ContainsKey($section)) { @($scopeMap[$section]).Count } else { 0 }
    $appCount   = if ($appPermsBySection.ContainsKey($section))  { @($appPermsBySection[$section]).Count }  else { 0 }
    $exoCount   = if ($exoRolesBySection.ContainsKey($section))  { @($exoRolesBySection[$section]).Count }  else { 0 }
    $compCount  = if ($compRolesBySection.ContainsKey($section)) { @($compRolesBySection[$section]).Count } else { 0 }
    [void]$sb.AppendLine("| $section | $services | $scopeCount | $appCount | $exoCount | $compCount |")
}

[void]$sb.AppendLine()
[void]$sb.AppendLine('## Section detail')
[void]$sb.AppendLine()

foreach ($section in $allSections) {
    [void]$sb.AppendLine("### $section")
    [void]$sb.AppendLine()

    # Services
    $services = if ($serviceMap.ContainsKey($section) -and $serviceMap[$section].Count -gt 0) {
        ($serviceMap[$section] -join ', ')
    } else { 'None — local-only collector' }
    [void]$sb.AppendLine("**Services touched:** $services")
    [void]$sb.AppendLine()

    # Delegated scopes
    if ($scopeMap.ContainsKey($section) -and $scopeMap[$section].Count -gt 0) {
        [void]$sb.AppendLine('**Delegated Microsoft Graph scopes**')
        [void]$sb.AppendLine()
        foreach ($scope in ($scopeMap[$section] | Sort-Object)) {
            [void]$sb.AppendLine("- ``$scope``")
        }
        [void]$sb.AppendLine()
    }

    # App permissions
    if ($appPermsBySection.ContainsKey($section)) {
        [void]$sb.AppendLine('**Microsoft Graph application permissions** (app-only auth)')
        [void]$sb.AppendLine()
        [void]$sb.AppendLine('| Permission | Reason |')
        [void]$sb.AppendLine('|---|---|')
        foreach ($p in ($appPermsBySection[$section] | Sort-Object Name -Unique)) {
            [void]$sb.AppendLine("| ``$($p.Name)`` | $($p.Reason) |")
        }
        [void]$sb.AppendLine()
    }

    # EXO RBAC role groups
    if ($exoRolesBySection.ContainsKey($section)) {
        [void]$sb.AppendLine('**Exchange Online RBAC role groups**')
        [void]$sb.AppendLine()
        [void]$sb.AppendLine('| Role group | Reason |')
        [void]$sb.AppendLine('|---|---|')
        foreach ($r in ($exoRolesBySection[$section] | Sort-Object Name -Unique)) {
            [void]$sb.AppendLine("| ``$($r.Name)`` | $($r.Reason) |")
        }
        [void]$sb.AppendLine()
    }

    # Compliance / directory roles
    if ($compRolesBySection.ContainsKey($section)) {
        [void]$sb.AppendLine('**Entra directory roles** (for Purview / Compliance access)')
        [void]$sb.AppendLine()
        [void]$sb.AppendLine('| Role | Reason |')
        [void]$sb.AppendLine('|---|---|')
        foreach ($r in ($compRolesBySection[$section] | Sort-Object Name -Unique)) {
            [void]$sb.AppendLine("| ``$($r.Name)`` | $($r.Reason) |")
        }
        [void]$sb.AppendLine()
    }
}

[void]$sb.AppendLine('## Behavior when a permission is missing')
[void]$sb.AppendLine()
[void]$sb.AppendLine('When a Graph / EXO / Purview API call fails due to a missing permission, the responsible collector emits `Status=''Unknown''` per `docs/CHECK-STATUS-MODEL.md`. The `CurrentValue` field surfaces what could not be collected, and `Remediation` calls out the exact missing permission so the user knows what to grant.')
[void]$sb.AppendLine()
[void]$sb.AppendLine('Concretely:')
[void]$sb.AppendLine()
[void]$sb.AppendLine('| Failure mode | Status emitted | Counted toward Pass% denominator? |')
[void]$sb.AppendLine('|---|---|---|')
[void]$sb.AppendLine('| Missing Graph scope (delegated) | Unknown | No |')
[void]$sb.AppendLine('| Missing Graph app role (app-only) | Unknown | No |')
[void]$sb.AppendLine('| EXO cmdlet not available (license/role) | NotLicensed | No |')
[void]$sb.AppendLine('| Tenant does not run the relevant service | NotApplicable | No |')
[void]$sb.AppendLine('| Section explicitly skipped via `-Section` filter | Skipped | No |')
[void]$sb.AppendLine('| Transient API error (timeout, throttle) | Unknown | No |')
[void]$sb.AppendLine()
[void]$sb.AppendLine('See `docs/CHECK-STATUS-MODEL.md` for the full status taxonomy and decision tree.')
[void]$sb.AppendLine()
[void]$sb.AppendLine('## Regenerating this document')
[void]$sb.AppendLine()
[void]$sb.AppendLine('```powershell')
[void]$sb.AppendLine('pwsh -NoProfile -File ./scripts/Build-PermissionsMatrix.ps1')
[void]$sb.AppendLine('```')
[void]$sb.AppendLine()
[void]$sb.AppendLine('Run this whenever you change the section-to-scope map (`AssessmentMaps.ps1`) or the permission definitions (`PermissionDefinitions.ps1`). Commit the regenerated `docs/reference/PERMISSIONS.md` alongside the source change. CI runs the script with `-Check` and fails the PR if the doc is out of sync.')
[void]$sb.AppendLine()

$generated = $sb.ToString()

# Normalize line endings for cross-platform parity (CI may be on Linux/Mac)
$generated = $generated -replace "`r`n", "`n"

# ------------------------------------------------------------------
# Output: Check mode vs Write mode
# ------------------------------------------------------------------
if ($Check) {
    if (-not (Test-Path -LiteralPath $OutputPath)) {
        Write-Error "[Build-PermissionsMatrix -Check] $OutputPath does not exist. Run without -Check to generate it."
        exit 1
    }
    $existing = Get-Content -LiteralPath $OutputPath -Raw
    $existing = $existing -replace "`r`n", "`n"
    if ($existing -eq $generated) {
        Write-Host "[Build-PermissionsMatrix -Check] $OutputPath is in sync with source maps." -ForegroundColor Green
        exit 0
    }
    Write-Host "[Build-PermissionsMatrix -Check] $OutputPath is OUT OF SYNC with source maps." -ForegroundColor Red
    Write-Host "  Run: pwsh -NoProfile -File ./scripts/Build-PermissionsMatrix.ps1" -ForegroundColor Yellow
    Write-Host "  Then commit the regenerated $OutputPath" -ForegroundColor Yellow
    exit 1
}

# Write mode
$outDir = Split-Path -Parent $OutputPath
if (-not (Test-Path -LiteralPath $outDir)) {
    New-Item -ItemType Directory -Path $outDir -Force | Out-Null
}
Set-Content -LiteralPath $OutputPath -Value $generated -NoNewline -Encoding UTF8
Write-Host "[Build-PermissionsMatrix] Wrote $OutputPath" -ForegroundColor Green
